### ISSUE TITLE
Error: setup Error: TypeError: Cannot read properties of undefined (reading 'mountpoint')

### ISSUE THREAD

**Issue by dexbotsdev** [EpicsDAO/solv#90]
solv@ssdnodes:~$ solv setup
Updated /home/solv/solv.config.json with new values.
Setting up Solana Validator ...
? Which solv types do you want to setup? MAINNET_VALIDATOR
? Which mainnet mode do you want to setup? JitoMev
JITO MEV Setup Mode on!
? Enter commission bps 1000
? Select region Amsterdam
? What is your commission rate? You can change it later (default: 10%) 7
Setting up MAINNET_VALIDATOR...
Error: setup Error: TypeError: Cannot read properties of undefined (reading 'mountpoint')
    at setup (/home/solv/.nodenv/versions/20.10.0/lib/node_modules/@epics-dao/solv/dist/index.js:288:1496)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async r.<anonymous> (/home/solv/.nodenv/versions/20.10.0/lib/node_modules/@epics-dao/solv/dist/index.js:288:3626)
    at async r.parseAsync (/home/solv/.nodenv/versions/20.10.0/lib/node_modules/@epics-dao/solv/dist/index.js:16:3980)
    at async main (/home/solv/.nodenv/versions/20.10.0/lib/node_modules/@epics-dao/solv/dist/index.js:336:831)

**Comment by POPPIN-FUMI** [comment]
Could you try with v3.3.5?

**Comment by t1ntech** [comment]
3.3.5 installed, same error. Installing RPC NODE & Validator.

**Comment by POPPIN-FUMI** [comment]
sh -c "$(curl -sSfL "https://storage.googleapis.com/epics-bucket/resource/solv/v3.3/install")"

I tried this install script and worked.
Please let me know if you still have an error!

**Comment by Vera0011** [comment]
Hello,
Same error here! It may be due to using a virtual machine (VirtualBox, Ubuntu live server 22.04.4 amd 64)?

**Comment by stevenkader** [comment]
Any solutions to this.  I am getting this also on Ubuntu 22.04 x64.  Thx.

**Comment by shenfu1991** [comment]
same error,Is it because my computer hardware configuration is too low? For example, the configuration cannot reach epyc 7743 and 512G ram?
,and logs is:

<pre>

solv@HL:~$ solv setup
Updated /home/solv/solv.config.json with new values.
Setting up Solana Validator ...
? Which solv types do you want to setup? RPC_NODE
? Enter your IP address to allow access to RPC NODE: 0.0.0.0
[sudo] password for solv: 
✔️ Firewall updated!
Setting up RPC_NODE...
Error: setup Error: TypeError: Cannot read properties of undefined (reading 'mountpoint')
    at setup (/home/solv/.local/share/pnpm/global/5/.pnpm/@epics-dao+solv@3.3.13/node_modules/@epics-dao/solv/dist/index.js:294:1613)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async t.<anonymous> (/home/solv/.local/share/pnpm/global/5/.pnpm/@epics-dao+solv@3.3.13/node_modules/@epics-dao/solv/dist/index.js:294:3291)
    at async t.parseAsync (/home/solv/.local/share/pnpm/global/5/.pnpm/@epics-dao+solv@3.3.13/node_modules/@epics-dao/solv/dist/index.js:16:3980)
    at async main (/home/solv/.local/share/pnpm/global/5/.pnpm/@epics-dao+solv@3.3.13/node_modules/@epics-dao/solv/dist/index.js:351:819)
</pre>

**Comment by POPPIN-FUMI** [comment]
Are you guys using VirtualBox?
If so, it is not recommended!
Could you please share what server instance is facing this problem?

**Comment by stevenkader** [comment]
I am using AWS :  m6i.12xlarge
![Screenshot 2024-04-08 at 5 21 26 PM](https://github.com/EpicsDAO/solv/assets/9343718/a575b8eb-63c2-4dfb-a15e-4a1712048f96)

**Comment by janbaranowski** [comment]
Same thing happenning running this in a clean ubuntu docker image:

Setting up MAINNET_VALIDATOR...
Error: setup Error: TypeError: Cannot read properties of undefined (reading 'mountpoint')
    at setup (/home/solv/.local/share/pnpm/global/5/.pnpm/@epics-dao+solv@3.3.15/node_modules/@epics-dao/solv/dist/index.js:299:1627)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async t.<anonymous> (/home/solv/.local/share/pnpm/global/5/.pnpm/@epics-dao+solv@3.3.15/node_modules/@epics-dao/solv/dist/index.js:299:3356)
    at async t.parseAsync (/home/solv/.local/share/pnpm/global/5/.pnpm/@epics-dao+solv@3.3.15/node_modules/@epics-dao/solv/dist/index.js:16:3980)
    at async main (/home/solv/.local/share/pnpm/global/5/.pnpm/@epics-dao+solv@3.3.15/node_modules/@epics-dao/solv/dist/index.js:356:819)

**Comment by POPPIN-FUMI** [comment]
It looks like AWS has some problems.
Can you guys come to solv discord to fix this?

https://discord.gg/J6qRD4KX

I think AWS's `lsblk -l` might be different from other instances.

**Comment by rluisr** [comment]
same here. Does anyone know how to solve it?

```
NAME  MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
loop0   7:0    0 61.9M  1 loop /snap/core20/1405
loop1   7:1    0 63.9M  1 loop /snap/core20/2264
loop2   7:2    0 79.9M  1 loop /snap/lxd/22923
loop3   7:3    0 44.7M  1 loop /snap/snapd/15534
loop4   7:4    0   87M  1 loop /snap/lxd/27948
sda     8:0    0   64G  0 disk
sda1    8:1    0    1M  0 part
sda2    8:2    0   64G  0 part /
```

**Comment by fbettag** [comment]
Hey guys, so i'm having the same issue with a really large VM on VMware. The Problem seems to be the .disks array which is not getting populated.

I've just added a console.log(is().disks) right before the error, and it returns [] (empty array).

So there seems to be something wrong with the hdd detection i guess.

```
Updated /home/solv/solv.config.json with new values.
Setting up Solana Validator ...
? Which solv types do you want to setup? RPC_NODE
? Enter your IP address to allow access to RPC NODE: 80.83.186.18
[sudo] password for solv: 
✔️ Firewall updated!
Setting up RPC_NODE...
[]
Error: setup Error: TypeError: Cannot read properties of undefined (reading 'mountpoint')
    at setup (/home/solv/.local/share/pnpm/global/5/.pnpm/@epics-dao+solv@3.3.19/node_modules/@epics-dao/solv/dist/index.js:299:1727)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async t.<anonymous> (/home/solv/.local/share/pnpm/global/5/.pnpm/@epics-dao+solv@3.3.19/node_modules/@epics-dao/solv/dist/index.js:299:3456)
    at async t.parseAsync (/home/solv/.local/share/pnpm/global/5/.pnpm/@epics-dao+solv@3.3.19/node_modules/@epics-dao/solv/dist/index.js:16:3980)
    at async main (/home/solv/.local/share/pnpm/global/5/.pnpm/@epics-dao+solv@3.3.19/node_modules/@epics-dao/solv/dist/index.js:356:819)
```

**Comment by fbettag** [comment]
since `is` is the value of `yve()`, and that gets defined as

```
function yve(){let e=(0,sk.execSync)("lsblk -l -b -o NAME,SIZE,MOUNTPOINT",{encoding:"utf8"}).split(`....
```

Now running that returns normal output:

```
solv@ubuntu-2004-lts:~$ lsblk -l -b -o NAME,SIZE,MOUNTPOINT
NAME                          SIZE MOUNTPOINT
loop0                     58314752 /snap/core18/2721
loop1                     58363904 /snap/core18/2812
loop2                     40996864 /snap/snapd/21184
loop3                     67014656 
loop4                     73728000 /snap/lxd/21029
loop5                     96292864 /snap/lxd/24061
loop6                     42393600 
loop7                     67051520 /snap/core20/2264
loop8                     67010560 /snap/core20/2182
loop9                     40615936 /snap/snapd/21465
sda                   214748364800 
sda1                       1048576 
sda2                    1073741824 /boot
sda3                  213671477248 
sr0                     1073741312 
ubuntu--vg-ubuntu--lv 213670428672 /
```

I'm guessing the following javascript magic boggles the array and thus misses the disk.

**Comment by stevenkader** [comment]
I got it working by making my main volume with OS 800 GB.

But I tried very power and expensive AWS server and was unable to catch-up.

**Comment by fbettag** [comment]
aaah, this could probably be the size check that follows if the disk is > 400gb or 850gb depending on what you're setting up.

**Comment by fbettag** [comment]
> I got it working by making my main volume with OS 800 GB.
> 
> But I tried very power and expensive AWS server and was unable to catch-up.

we came to the same conclusian  :) mine is now working too.

**Comment by stevenkader** [comment]
> > I got it working by making my main volume with OS 800 GB.
> > But I tried very power and expensive AWS server and was unable to catch-up.
> 
> we came to the same conclusion :) mine is now working too.

Were you able to catch-up yet?

**Comment by fbettag** [comment]
not yet

```
[2024-04-19T12:18:31.090839013Z INFO  solana_download_utils] downloaded 45691025552 bytes 64.4% 21319186.0 bytes/s
[2024-04-19T12:18:37.091242308Z INFO  solana_download_utils] downloaded 45819556320 bytes 64.6% 21420356.0 bytes/s
[2024-04-19T12:18:43.091653848Z INFO  solana_download_utils] downloaded 45948050392 bytes 64.8% 21414214.0 bytes/s
[2024-04-19T12:18:49.091876916Z INFO  solana_download_utils] downloaded 46076543688 bytes 65.0% 21414758.0 bytes/s
```

**Comment by stevenkader** [comment]
After it reaches 100% run  'solv get catchup'  it will then show you if you are staying up to date or falling behind.  I was always falling behind.  Thx.

**Comment by fbettag** [comment]
i'll keep you posted, currently at 95%, my guess is the disks are too slow (even tho i have sata ssd only storage)

**Comment by fbettag** [comment]
ah yeah, i need to add more cpus to the VM.

[2024-04-19T12:53:47.414092964Z ERROR solana_validator] Failed to start validator: "PoH is slower than cluster target tick rate! mine: 767312631 cluster: 400000000."

**Comment by fbettag** [comment]
> > ah yeah, i need to add more cpus to the VM.
> > [2024-04-19T12:53:47.414092964Z ERROR solana_validator] Failed to start validator: "PoH is slower than cluster target tick rate! mine: 767312631 cluster: 400000000."
> 
> I went as high as 98 and still had trouble catching up

apparently it's just a missing log line. there is also no log line for 0 % :)

**Comment by p0st1t** [comment]
Hello, sorry, i'm not sure to understand..

I have the same issue. We need a disk with 800 go minimum? Where can i find the prerequisites to start my validator with solv please?

**Comment by fbettag** [comment]
> I'm scared to buy a VPS at 250$ for nothing x)

Then operating a validator node might not be for you. it's a financial risk and 250$ is going to be the least of it.

**Comment by fbettag** [comment]
Operating validator nodes is not a scheme to make money. It's a way of supporting the Solana Ecosystem. Yes you get rewarded, but there are risks as there are with anything where you have to go money-first.

**Comment by p0st1t** [comment]
I was able to install my jit-mev valdiator and read / send tx.

But now i dont understand how to use the jito/mev-bot, they ask a geyser access_token, i don't know where to find it.

And, i'm not sure : the jito/mev-bot allow us to run a mev bot on it or no please?
